Development (#113)
* Update dependabot.yml
* Update auto_comment_on_pr.yml

diff --git a/.github/workflows/auto_comment_on_pr.yml b/.github/workflows/auto_comment_on_pr.yml
--- a/.github/workflows/auto_comment_on_pr.yml
+++ b/.github/workflows/auto_comment_on_pr.yml
@@ -1,7 +1,9 @@
 name: Auto-comment on PR
 on:
   pull_request:
-    types: [opened]
+    types: 
+      - opened
+      - synchronize
 
 jobs:
   comment:
@@ -25,16 +27,22 @@ jobs:
       run: |
         set -e  # Stop execution on any error
         
+        # Initialize or clean up files_linked.txt
+        > files_linked.txt
+
         PR_ID=$(jq -r ".pull_request.number" "$GITHUB_EVENT_PATH") || exit 1
         PR_AUTHOR=$(jq -r ".pull_request.user.login" "$GITHUB_EVENT_PATH") || exit 1
         PR_BRANCH=$(jq -r ".pull_request.head.ref" "$GITHUB_EVENT_PATH") || exit 1
-    
+        PR_TITLE=$(jq -r '.pull_request.html_url' $GITHUB_EVENT_PATH) || exit 1
+        PR_BODY=$(jq -r '.pull_request.body' $GITHUB_EVENT_PATH) || exit 1
+        PR_LABELS=$(jq -r '.pull_request.labels[]?.name' "$GITHUB_EVENT_PATH" | tr '\n' ', ') || exit 1
+
         REPO_URL="https://github.com/${{ github.repository }}/blob/$PR_BRANCH"
         
         # Fetch Files Changed details
         FILES_JSON=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
           https://api.github.com/repos/${{ github.repository }}/pulls/$PR_ID/files) || exit 1
-    
+
         FILES_LINKED=""
         
         # Iterate through each file to get details
@@ -48,13 +56,21 @@ jobs:
           DELETIONS=$(_jq '.deletions')
           CHANGES=$(_jq '.changes')
           
-          FILES_LINKED+="- [$FILE_NAME]($REPO_URL/$FILE_NAME) (Additions: $ADDITIONS, Deletions: $DELETIONS, Changes: $CHANGES)"$'\n'
+          echo "- [$FILE_NAME]($REPO_URL/$FILE_NAME) (Additions: $ADDITIONS, Deletions: $DELETIONS, Changes: $CHANGES)" >> files_linked.txt    
+          
         done
-        
-        echo "PR_ID=$PR_ID" >> $GITHUB_ENV
-        echo "PR_AUTHOR=$PR_AUTHOR" >> $GITHUB_ENV
-        echo "FILES_LINKED=$FILES_LINKED" >> $GITHUB_ENV
 
+        echo "PR_ID=$PR_ID" >> "$GITHUB_ENV"
+        echo "PR_AUTHOR=$PR_AUTHOR" >> "$GITHUB_ENV"
+        echo "PR_TITLE=$PR_TITLE" >> "$GITHUB_ENV"
+        echo "PR_BODY=$PR_BODY" >> "$GITHUB_ENV"
+        echo "PR_LABELS=$PR_LABELS" >> "$GITHUB_ENV"
+        {
+          echo 'FILES_LINKED<<EOF'
+          cat files_linked.txt
+          echo EOF
+        } >> "$GITHUB_ENV"
+        
     - name: Set Workflow Status
       run: echo "WORKFLOW_STATUS=success" >> $GITHUB_ENV
       if: success()
@@ -66,17 +82,30 @@ jobs:
         echo "An error occurred. Check the logs for details."
 
     - name: Add comment to PR
-      uses: thollander/actions-comment-pull-request@v2
-      with:
-        message: |
-          Hey @${{ env.PR_AUTHOR }},
-          - **PR Number**: [#${{ env.PR_ID }}](https://github.com/${{ github.repository }}/pull/${{ env.PR_ID }})
-          - **Labels**: ${{ env.LABELS }}
-          - **Workflow Status**: ${{ env.WORKFLOW_STATUS }}
-          
-          **Files Changed:**
-          ${{ env.FILES_LINKED }}
-          
-          Please ensure all tests and checks are passed. We'll be reviewing it shortly.
-          For more details, please check [our contribution guide](https://github.com/${{ github.repository }}/blob/main/CONTRIBUTING.md).
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      run: |
+        FILES_LINKED=$(echo "$FILES_LINKED" | sed -E 's/["“”]/\\"/g')
+        
+        COMMENT_BODY=$(jq -n \
+                        --arg pr_author "$PR_AUTHOR" \
+                        --arg pr_title "$PR_TITLE" \
+                        --arg pr_body "$PR_BODY" \
+                        --arg repo "${{ github.repository }}" \
+                        --arg pr_labels "$PR_LABELS" \
+                        --arg files_linked "$FILES_LINKED" \
+                        '{
+                          "body": ("Hey @" + $pr_author + ",\n" +
+                                  "- **PR Title**: " + $pr_title + "\n" +
+                                  "- **PR Body**: " + $pr_body + "\n" +
+                                  "- **Labels**: " + $pr_labels + "\n" +
+                                  "- **Workflow Status**: success\n\n" +
+                                  "**Files Changed:**\n" + $files_linked + "\n\n" +
+                                  "Please ensure all tests and checks are passed. We will examine it shortly.\n" +
+                                  "For more details, please check [our contribution guide](https://github.com/" + $repo + "/blob/main/CONTRIBUTING.md).")
+                        }')
+        
+        curl \
+          -X POST \
+          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+          -H "Content-Type: application/json" \
+          -d "$COMMENT_BODY" \
+          "https://api.github.com/repos/${{ github.repository }}/issues/$PR_ID/comments"
